= todo-backend: quickstart for backend deployment on OpenShift
:toc:               left
:icons:             font
:idprefix:
:idseparator:       -
:keywords:          openshift,galleon,helm
:level:             Intermediate
:technologies:      JPA, JAX-RS, OpenShift, Galleon

[abstract]
The `todo-backend` quickstart demonstrates how to implement a backend that exposes a Rest API with JAX-RS
to manage a list of ToDo which are persisted in a database with JPA.

This quickstart shows how to setup a local deployment of this backend as well as a deployment on OpenShift to connect
to a PostgreSQL database also hosted on OpenShift

== What is it?

The `tasks-rs` quickstart demonstrates how to implement  a backend that exposes a Rest API with JAX-RS
to manage a list of ToDo which are persisted in a database with JPA.

* The backend exposes a REST API to manage a list of todos that complies with the specs defined at https://todobackend.com/specs/index.html[todobackend.com].
* It requires a connection to a PostgreSQL database to persist the todos.

This backend is deployed using Bootable Jar.

== Package the quickstart

[source,options="nowrap"]
----
$ mvn clean package -P bootable-jar-openshift
----

== Run the backend locally

=== Local PostGreSQL database

Before running the backend locally, we need to have a local PostgreSQL database that we can connect to.
We use the `postgresql` docker image to create one:

[source,options="nowrap"]
----
$ docker run --name todos-db -e POSTGRES_USER=todos -e POSTGRES_PASSWORD=mysecretpassword  -p 5432:5432 postgres
----

This will create a database named `todos-db` that we can connect to on `localhost:5432` with the credentials `todos / mysecretpassword`.

=== Run the backend

With the PostgreSQL database running, we can start the backend by passing the required environment variables to connect to the database:

[source,options="nowrap"]
----
$ POSTGRESQL_DATABASE=todos \
  POSTGRESQL_USER=todos \
  POSTGRESQL_PASSWORD=mysecretpassword \
  POSTGRESQL_DATASOURCE=ToDos \
  POSTGRESQL_SERVICE_HOST=localhost \
  POSTGRESQL_SERVICE_PORT=5432 \
  java -jar target/todo-backend-bootable.jar
...
14:41:58,111 INFO  [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0010: Deployed "todo-backend.war" (runtime-name : "ROOT.war")
...
----

The backend is running and we can use the REST API to manage a list of todos:

[source,options="nowrap"]
----
# get a list of todos
$ curl http://localhost:8080
[]

# create a todo with the title "Hello, WildFly!"
$ curl -X POST -H "Content-Type: application/json"  -d '{"title": "Hello, WildFly!"}' http://localhost:8080/
{"completed":false,"id":1,"order":0,"title":"Hello, WildFly!","url":"https://localhost:8080/1"}%

# get a list of todos with the one that was just created
$ curl http://localhost:8080
[{"completed":false,"id":1,"order":0,"title":"Hello, WildFly!","url":"https://localhost:8080/1"}
----

== Run the backend on OpenShift

=== Prerequisites

* You must be logged in OpenShift and have a `oc` client to connect to OpenShift
* https://helm.sh[Helm] must be installed to deploy the backend on OpenShift.

Once you have installed Helm, you need to add the repository that provides Helm Charts for WildFly:

[source,options="nowrap"]
----
$ helm repo add wildfly https://jmesnil.github.io/wildfly-charts
"wildfly" has been added to your repositories
$ helm search repo wildfly
NAME                    CHART VERSION   APP VERSION     DESCRIPTION
wildfly/wildfly         0.9.5           22.0            Build and Deploy WildFly applications on OpenShift
----

=== Deploy PostGreSQL database on OpenShift

[source,options="nowrap"]
----
$ oc new-app postgresql-ephemeral \
   -p DATABASE_SERVICE_NAME=todos-db \
   -p POSTGRESQL_DATABASE=todos
----

This will create a PostgreSQL database named `todos` on OpenShift that can be accessed on the port `5432` on the service `todos-db`.
We don't need to copy the credentials to connect to the database as we will retrieve them later using the `todos-db` secret that was created
when the database was deployed.

=== Deploy the backend on OpenShift

The backend will be deployed on OpenShift with a Helm Chart for WildFly.

[source,options="nowrap"]
----
$ helm install todo-backend -f todo-backend.yaml wildfly/wildfly
NAME: todo-backend
...
STATUS: deployed
REVISION: 1
----

Let's wait for the application to be built and deployed:

[source,options="nowrap"]
----
$ oc get dc/todo-backend -w
NAME           REVISION   DESIRED   CURRENT   TRIGGERED BY
todo-backend   0          3         0         config,image(todo-backend:latest)
...
todo-backend   1          3         3         config,image(todo-backend:latest)
----

The Helm Chart for this quickstart contains all the information to build an image from the source code using Bootable Jar:

[source,options="nowrap"]
----
build:
  uri: https://github.com/wildfly/quickstart.git
  mode: bootable-jar
----

The Helm Chart also contains the environment variables required to connect to the PostgreSQL database.
In local deployment the credentials were passed directly as the values of the environment variables.
For OpenShift, we rely on secrets so that the credentials are never copied outside OpenShift:

[source,options="nowrap"]
----
deploy:
  env:
    - name: POSTGRESQL_PASSWORD
      valueFrom:
        secretKeyRef:
          key: database-password
          name: todos-db
----

When the application is deployed, the value for the `POSTGRESQL_PASSWORD` will be taken from the key `database-password`
in the secrets `todos-db`.

=== Use the todobackend Web application

Once the backend is deployed on OpenShift, it can be accessed from the route `todo-backend`.
Let's find the host that we can use to connect to this backend:

[source,options="nowrap"]
----
$ oc get route todo-backend -o jsonpath="{.spec.host}"
todo-backend-jmesnil1-dev.apps.sandbox.x8i5.p1.openshiftapps.com
----

This value will be different for every installation of the backend.

[NOTE]
====
Make sure to prepend the host with `https://` to be able to connect to the backend from the ToDo Backend Specs or Client
====

We can verify that this application is properly working as a ToDo Backend by running its https://todobackend.com/specs/index.html[specs] on it.


Once all tests passed, we can use the https://todobackend.com/client/index.html[todobackend client] to have a Web application connected to the backend.

=== Clean up

The backend can be deleted from OpenShift by running the command:

[source,options="nowrap"]
----
$ helm delete todo-backend
release "todo-backend" uninstalled
----