= helloworld-rs: Helloworld Using Jakarta API for RESTful Web Services
:level: Intermediate
:technologies: CDI, JAX-RS
:toc: left

[abstract]
The `helloworld-rs` quickstart demonstrates a simple Hello World application, bundled and deployed as a WAR, that uses JAX-RS to say Hello.

== Introduction

The `helloworld-rs` quickstart demonstrates the use of CDI and JAX-RS in {productNameFull}.

== Package the Quickstart

[source]
----
mvn clean package
----

This create the `target/server` directory that contains the server and the WAR deployment in it.

== Start the Quickstart

[source]
----
cd target/server
./bin/standalone.sh
----

You should see a message in the server log indicating that the archive deployed successfully.

== Access the Quickstart

The quickstart can be accessed from http://localhost:8080/:
* The JSON content can be viewed by accessing the URL: http://localhost:8080/rest/json
* The XML content can be viewed by accessing the URL: http://localhost:8080/rest/xml

You can try to access the JSON content by running the command:

[source]
----
curl http://localhost:8080/rest/json
----

It will display the following output

[source,json]
----
{"result":"Hello World!"}
----

== Run the Integration Tests

You can run integration tests on the quickstart using Arquillian tests by running the command:

[source]
----
mvn clean verify
----

== Cloud Integration

=== Build the Application Image

You can build a Docker application image that contains the server and the quickstart by running the command:

[source]
----
mvn -Pcloud-server clean package docker:build
----

This will create a Docker image named `helloworld-rs`.

[NOTE]
====
The `cloud-server` Maven profile is activated to prepare the server for cloud deployment.
====

=== Run the Application Image

You can run the application image by executing the command:

[source]
----
docker run -p8080:8080 helloworld-rs
----

=== Access the Quickstart from the Application Image

The quickstart can be accessed from http://localhost:8080/:

You can try to access the JSON content by running the command:

[source]
----
curl http://localhost:8080/rest/json
----

It will display the following output

[source,json]
----
{"result":"Hello World!"}
----